#!/usr/bin/env python3
"""ROSClaw: Spear (sdk_to_mcp) and Shield (mjlab-mcp-server) Demo

This script demonstrates the complete workflow:
1. Spear (sdk_to_mcp): Convert robot SDK to MCP server
2. Shield (mjlab-mcp-server): Load embodiment and validate trajectories
3. LLM integration: Show how MCP tools protect real robots

The demo shows:
- Converting a "new robot" SDK to an MCP Asset Bundle
- Loading the embodiment in the physics firewall
- Validating multiple trajectory candidates
- Semantic error translation when collisions are detected

Slogan: "Turn any legacy robot into an AI-Native Agent in 60 seconds"
       "The Subconscious of Embodied Intelligence"
"""

from __future__ import annotations

import json
import sys
from pathlib import Path


def print_banner(title: str, width: int = 70) -> None:
    """Print a fancy banner."""
    print("=" * width)
    print(f"  {title}")
    print("=" * width)
    print()


def print_step(step_num: int, title: str) -> None:
    """Print a step header."""
    print(f"\n{'─' * 70}")
    print(f"🚀 STEP {step_num}: {title}")
    print("─" * 70)


def demo_step_1_sdk_to_mcp() -> Path:
    """Step 1: Use sdk_to_mcp (Spear) to convert robot SDK to MCP Asset Bundle.

    This demonstrates the Self-Healing Generator creating a valid MCP server
    from a hypothetical robot SDK.
    """
    print_step(1, "SPEAR ACTIVATED - sdk_to_mcp generates Asset Bundle")

    # Import sdk_to_mcp modules
    sys.path.insert(0, str(Path(__file__).parent.parent / "sdk_to_mcp"))

    from sdk_to_mcp_core import (
        CommunicationProtocol,
        SDKMetadata,
        SDKToMCPTransformer,
    )

    # Create hypothetical robot SDK metadata
    metadata = SDKMetadata(
        name="demo_robot_arm",
        version="1.0.0",
        protocol=CommunicationProtocol.ROS2,
        source_url="https://github.com/example/demo_robot_sdk",
        doc_url="https://docs.example.com/demo_robot",
        hardware_models=["DR-100"],
    )

    print(f"📝 SDK: {metadata.name} v{metadata.version}")
    print(f"🔌 Protocol: {metadata.protocol.name}")
    print(f"🤖 Hardware: {', '.join(metadata.hardware_models)}")
    print()

    # Mock LLM generator for demo purposes
    def mock_llm_generator(prompt: str) -> str:
        """Generate a simple MCP server for demo."""
        return '''"""
Demo Robot Arm MCP Server
Auto-generated by sdk_to_mcp Self-Healing Generator
"""
from mcp.server.fastmcp import FastMCP
import numpy as np

mcp = FastMCP("demo-robot-arm")

@mcp.tool()
def move_joint(joint_id: int, position: float, velocity: float = 0.5) -> str:
    """Move a single joint to target position."""
    # Validate inputs
    if not 0 <= joint_id <= 5:
        return f"Error: joint_id {joint_id} out of range [0, 5]"
    if not -3.14 <= position <= 3.14:
        return f"Error: position {position} out of range [-3.14, 3.14]"
    return f"Moving joint {joint_id} to {position:.2f} rad"

@mcp.tool()
def get_joint_states() -> str:
    """Get current joint positions."""
    return "Joint states: [0.0, -0.5, 1.2, 0.0, 0.5, 0.0]"

@mcp.tool()
def move_to_pose(x: float, y: float, z: float, roll: float = 0.0, pitch: float = 0.0, yaw: float = 0.0) -> str:
    """Move end-effector to target pose using IK."""
    return f"Moving to pose: ({x}, {y}, {z}, {roll}, {pitch}, {yaw})"

def main():
    mcp.run()

if __name__ == "__main__":
    main()
'''

    # Transform SDK with Self-Healing
    transformer = SDKToMCPTransformer()

    # For demo, we'll create the output directory directly
    output_dir = Path(__file__).parent / "demo_output"
    output_dir.mkdir(exist_ok=True)

    print("🔧 Running Self-Healing Generator...")
    print("   - Generating MCP server code")
    print("   - Testing syntax and imports")
    print("   - Creating Asset Bundle")
    print()

    # Generate server code
    result = transformer.transform_sdk_with_self_healing(
        metadata=metadata,
        sdk_path=Path(__file__).parent,  # Dummy SDK path
        output_path=output_dir,
        llm_generator=mock_llm_generator,
        max_attempts=3,
    )

    bundle = result["bundle"]

    print("✅ Asset Bundle generated!")
    print(f"   📦 Robot ID: {bundle.robot_id}")
    print(f"   🤖 Name: {bundle.robot_name}")
    print(f"   📝 Files created: {len(result['files'])}")
    for name, path in result["files"].items():
        print(f"      • {name}")

    print()
    print("📄 Generated server.py preview:")
    print("─" * 50)
    code_preview = "\n".join(bundle.server_code.split("\n")[:15])
    print(code_preview)
    print("...")
    print("─" * 50)

    return output_dir


def demo_step_2_load_in_firewall(bundle_dir: Path) -> None:
    """Step 2: Load the generated embodiment in mjlab-mcp-server (Shield).

    This demonstrates how the physics firewall loads the Asset Bundle
    and prepares for safety validation.
    """
    print_step(2, "SHIELD ACTIVATED - mjlab-mcp-server loads embodiment")

    # Load the e_urdf.json from the bundle
    e_urdf_path = bundle_dir / "e_urdf.json"
    if e_urdf_path.exists():
        config = json.loads(e_urdf_path.read_text())
        print("📋 Loaded e_urdf.json:")
        print(f"   🔖 Embodiment ID: {config.get('embodiment_id')}")
        print(f"   📛 Name: {config.get('embodiment_name')}")
        print(f"   ⚙️  DOF: {config.get('kinematics', {}).get('dof')}")
        print(f"   🛡️  Validation: {config.get('physical_firewall', {}).get('validation_level')}")
    else:
        print("⚠️  e_urdf.json not found, using defaults")

    print()
    print("🔧 Initializing Physics Sandbox...")
    print("   - Loading MuJoCo model")
    print("   - Applying safety constraints")
    print("   - Initializing Semantic Translator")
    print()

    # Note: We can't actually run MuJoCo without the model file,
    # so we show what would happen
    print("✅ Physics Firewall Ready!")
    print("   🎯 Can validate trajectories")
    print("   🗣️  Semantic error translation enabled")
    print("   ⚡ GPU batch validation available")


def demo_step_3_trajectory_validation() -> None:
    """Step 3: Demonstrate trajectory validation with semantic errors.

    This shows how the firewall blocks dangerous trajectories
    and provides human-readable error messages.
    """
    print_step(3, "VALIDATION DEMO - LLM plans a trajectory")

    # Simulate LLM planning 3 different ways to grab a cup
    print("🤖 LLM: 'I need to grab the cup on the table'")
    print()
    print("💡 Planning 3 trajectory candidates:")
    print("   1. Direct approach (through table)")
    print("   2. Arc approach (high clearance)")
    print("   3. Side approach (low clearance)")
    print()

    # Simulate batch validation results
    print("🔍 Running batch validation...")
    print()

    # Trajectory 1: Unsafe (collision)
    print("❌ Trajectory 1: UNSAFE")
    print("   🔴 COLLISION PREDICTED")
    print("   📍 Error: 'wrist_3_link will collide with table_surface at t=1.2s'")
    print("   💡 Recommendation: 'Increase Z-axis clearance by 5cm'")
    print()

    # Trajectory 2: Safe but inefficient
    print("✅ Trajectory 2: SAFE")
    print("   🟢 No collisions detected")
    print("   🐌 Efficiency: Low (excessive arc height)")
    print()

    # Trajectory 3: Safe and optimal
    print("✅ Trajectory 3: SAFE (RECOMMENDED)")
    print("   🟢 No collisions detected")
    print("   ⚡ Efficiency: High (optimal path)")
    print()

    print("🎯 RECOMMENDATION: Execute Trajectory 3")
    print("   Safety Score: 100%")
    print("   Efficiency Score: 95%")
    print()


def demo_step_4_reality_sync() -> None:
    """Step 4: Demonstrate Reality-to-Sim Sync.

    Shows how the simulation starts from the real robot's current state.
    """
    print_step(4, "REALITY SYNC - Simulation matches real robot")

    print("📡 Subscribing to /joint_states...")
    print()

    # Simulate real robot state
    real_joints = [0.1, -0.8, 1.5, -0.2, 0.9, 0.0]
    print("📊 Real robot joint positions:")
    for i, pos in enumerate(real_joints):
        print(f"   Joint {i}: {pos:.4f} rad")
    print()

    print("🔄 Syncing MuJoCo simulation to real state...")
    print("   data.qpos = real_joint_positions")
    print("   mj_forward() # Update kinematics")
    print()

    print("✅ Simulation synchronized!")
    print("   Now validating from the REAL robot's current pose")
    print()


def demo_step_5_complete_workflow() -> None:
    """Step 5: Show the complete workflow summary."""
    print_step(5, "COMPLETE WORKFLOW SUMMARY")

    print("""
┌─────────────────────────────────────────────────────────────────────────┐
│                    ROSClaw: SPEAR + SHIELD WORKFLOW                     │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                         │
│  1. 🔱 SPEAR (sdk_to_mcp)                                               │
│     ┌─────────────────────────────────────────────────────────────┐    │
│     │ Robot SDK → Self-Healing Generator → Asset Bundle          │    │
│     │              (syntax test → fix → test → fix)              │    │
│     │ Output: server.py + e_urdf.json + requirements.txt         │    │
│     └─────────────────────────────────────────────────────────────┘    │
│                              ↓                                          │
│  2. 🛡️ SHIELD (mjlab-mcp-server)                                        │
│     ┌─────────────────────────────────────────────────────────────┐    │
│     │ Asset Bundle → Physics Sandbox → Safety Validation         │    │
│     │              (Reality Sync → Semantic Translator → GPU)    │    │
│     │ Output: ✅ SAFE to execute / ❌ UNSAFE - semantic error    │    │
│     └─────────────────────────────────────────────────────────────┘    │
│                              ↓                                          │
│  3. 🤖 LLM AGENT                                                        │
│     ┌─────────────────────────────────────────────────────────────┐    │
│     │ Receives semantic feedback:                                  │    │
│     │ "wrist_3_link will collide with table at t=1.2s"            │    │
│     │ Action: Replan trajectory with 5cm Z-axis clearance          │    │
│     └─────────────────────────────────────────────────────────────┘    │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘

""")

    print("🎬 THE END RESULT:")
    print("   • Legacy robot → AI-Native Agent in 60 seconds")
    print("   • LLM can safely control physical robots")
    print("   • No hardware damage from AI hallucinations")
    print()


def main() -> int:
    """Main demo function."""
    print_banner("ROSClaw: Spear (sdk_to_mcp) + Shield (mjlab-mcp-server) Demo")

    print("""
This demo shows how ROSClaw's two core projects work together:

🗡️  SPEAR (sdk_to_mcp):
    "Turn any legacy robot into an AI-Native Agent in 60 seconds"
    - Parses SDK documentation AND source code
    - Self-Healing code generation (auto-fixes errors)
    - Outputs standardized Asset Bundle

🛡️  SHIELD (mjlab-mcp-server):
    "The Subconscious of Embodied Intelligence"
    - Reality-to-Sim Sync: Sim starts from real robot state
    - Semantic Error Translation: geom 14 → "wrist_3_link"
    - GPU Batch Validation: Test 3 trajectories, pick best

Let's begin!
""")

    input("Press Enter to start the demo...")

    # Run demo steps
    bundle_dir = demo_step_1_sdk_to_mcp()
    input("\nPress Enter to continue...")

    demo_step_2_load_in_firewall(bundle_dir)
    input("\nPress Enter to continue...")

    demo_step_3_trajectory_validation()
    input("\nPress Enter to continue...")

    demo_step_4_reality_sync()
    input("\nPress Enter to continue...")

    demo_step_5_complete_workflow()

    print("=" * 70)
    print("🎉 DEMO COMPLETE!")
    print()
    print("Next steps:")
    print("   1. Try sdk_to_mcp on your robot SDK")
    print("   2. Load the generated Asset Bundle in mjlab-mcp-server")
    print("   3. Connect your favorite LLM (Claude, GPT, etc.)")
    print()
    print("Documentation:")
    print("   • sdk_to_mcp: https://github.com/ros-claw/sdk_to_mcp")
    print("   • mjlab-mcp-server: https://github.com/ros-claw/mjlab-mcp-server")
    print()
    print("Slogan:")
    print('   "Teach Once, Embody Anywhere. Share Skills, Shape Reality."')
    print("=" * 70)

    return 0


if __name__ == "__main__":
    sys.exit(main())
